services:
  etcd:
    image: "bitnami/etcd:latest"
    container_name: etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: yes

  fluentd:
    build: fluentd
    depends_on:
      - rabbitmq
    network_mode: host

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    network_mode: host
    # ports:
    #   - "15672:15672"

  simuhub:
    build: simuhub
    depends_on:
      - etcd
    ports:
      - "80:8080"
    environment:
      ETCD_URI: "etcd:2379"
      ETCD_KEY: config

  simulog:
    build: simulog
    deploy:
      replicas: 10
    depends_on:
      - fluentd
      - etcd
    environment:
      ETCD_URI: "etcd:2379"
      ETCD_KEY: config
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "docker.simulog.{{.ID}}"
